close all;
start_plot=65000+256;
end_plot=65000+256*2;
figure(1);
plot(ADEBUG_TABLE_Fsymb_pulse(start_plot:end_plot));
hold on;
plot(ADEBUG_TABLE_Fsymb_ovr_pulse(start_plot:end_plot)*0.5);
hold on;
plot(ADEBUG_TABLE_Fsymb_x2_pulse(start_plot:end_plot)*0.25);
hold on;
plot(data_in_I(start_plot:end_plot));
hold on;
plot(ADEBUG_TABLE_data_resample_I(start_plot:end_plot),'+');
hold on;
plot(ADEBUG_TABLE_data_rrc_filtered_I(start_plot:end_plot),'x');
hold on;
plot(ADEBUG_TABLE_data_symbols_I(start_plot:end_plot),'o');
hold on;
##plot(ADEBUG_TABLE_nco_accu_tmp_fsymb(start_plot:end_plot)/2^32+2);
##hold on;
##plot(ADEBUG_TABLE_nco_accu_tmp_fsymb_xovr(start_plot:end_plot)/2^32+2);
##plot(ADEBUG_TABLE_Fsymb_fe_pulse(start_plot:end_plot),'.-');